Repository Untoc-Web-Develop/Untoc-Back, pull requests merged in 2024-03, with the labels that each got.

#26 feat : about and history
  src/controllers/about.controller.ts
  src/entities/about-block.entity.ts
  src/entities/about.entity.ts
  src/entities/history.entity.ts
  src/entities/index.ts
  src/modules/about.module.ts
  src/modules/index.ts
  src/services/about/about.service.ts
  src/services/about/dto/get-abouts.dto.ts
Labels: Feat

#29 fix: find applyQuestion 순서 통일
  src/services/apply/apply.service.ts
Labels: Fix

#30 Feature/admin auth #27
  src/auth/auth.service.ts
  src/auth/guard/admin.guard.ts
  src/auth/guard/login.guard.ts
  src/common/error.ts
  src/controllers/whitelist.controller.ts
  src/entities/badge.entity.ts
  src/modules/whitelist.module.ts
  src/services/user/user.service.ts
Labels: Feat

#32 Feature/Module 통합 #31
  src/app.module.ts
  src/auth/auth.module.ts
  src/common/error.ts
  src/controllers/auth.controller.ts
  src/controllers/index.ts
  src/controllers/whitelist.controller.ts
  src/entities/index.ts
  src/entities/post.entity.ts
  src/entities/team.entity.ts
  src/entities/vote.entity.ts
  src/modules/about.module.ts
  src/modules/apply.module.ts
  src/modules/index.ts
  src/modules/whitelist.module.ts
  src/services/auth/auth.service.ts
  src/services/auth/dto/login.dto.ts
  src/services/auth/dto/register.dto.ts
  src/services/auth/guard/login.guard.ts
  src/services/auth/payload/access.payload.ts
  src/services/auth/payload/refresh.payload.ts
  src/services/index.ts
Labels: Refector

#33 Badge_log_Id change
  src/entities/badge-log.entity.ts
  src/entities/base.entity.ts
Labels: Feat

#34 error when email not exist
  src/services/auth/auth.service.ts
Labels: Fix

#35 Feature/실사용 배포 준비
  src/controllers/auth.controller.ts
  src/entities/file.entity.ts
  src/services/auth/auth.service.ts
  src/services/auth/payload/access.payload.ts
Labels: Feat

#36 fix : string -> longtext
  src/entities/apply-question.entity.ts
  src/entities/apply-setting.entity.ts
  src/entities/apply-value.entity.ts
Labels: Fix

#37 feat : add admin auth for apply
  src/controllers/apply.controller.ts
Labels: Feat

#39 Feature/토큰만료시_500에러_#38
  src/services/auth/auth.service.ts
  src/services/auth/guard/login.guard.ts
Labels: Fix

#41 refactor: 지원서 applyQuestion 정렬
  src/services/apply/apply.service.ts
Labels: Refector

#48 Feature/팀 api #45
  src/controllers/index.ts
  src/controllers/team.controller.ts
  src/entities/index.ts
  src/entities/team-link.entity.ts
  src/entities/team.entity.ts
  src/services/index.ts
  src/services/team/dto/get-team-list.dto.ts
  src/services/team/dto/get-team.dto.ts
  src/services/team/dto/post-team.dto.ts
  src/services/team/team.service.ts
Labels: Feat

#46 Feature/게시판 기능 구현 #17
  package-lock.json
  package.json
  src/app.module.ts
  src/controllers/auth.controller.ts
  src/controllers/board.controller.ts
  src/controllers/email.controller.ts
  src/controllers/index.ts
  src/controllers/post.controller.ts
  src/entities/board.entity.ts
  src/entities/email.entity.ts
  src/entities/index.ts
  src/entities/post.entity.ts
  src/services/auth/auth.service.ts
  src/services/auth/dto/patch-password.dto.ts
  src/services/auth/dto/post-forget.dto.ts
  src/services/board/board.service.ts
  src/services/board/dto/post-create.dto.ts
  src/services/email/dto/post-send.dto.ts
  src/services/email/dto/post-verify.dto.ts
  src/services/email/email.service.ts
  src/services/index.ts
  src/services/post/dto/get-read.dto.ts
  src/services/post/dto/patch-update.dto.ts
  src/services/post/dto/post-create.dto.ts
  src/services/post/post.service.ts
Labels: Feat

#51 feat: whitelist name 필드 생성 및 phoneNumber 필드 삭제
  src/entities/whitelist.entity.ts
  src/services/auth/auth.service.ts
  src/services/whitelist/dto/get-whitelist.dto.ts
  src/services/whitelist/dto/post-whitelist.dto.ts
  src/services/whitelist/whitelist.service.ts
Labels: Feat

#52 feat: generation 필드 추가
  src/entities/whitelist.entity.ts
  src/services/whitelist/dto/get-whitelist.dto.ts
  src/services/whitelist/dto/post-whitelist.dto.ts
  src/services/whitelist/whitelist.service.ts
Labels: Feat

#53 Feature/회원 관리 기능 추가 #50
  src/controllers/auth.controller.ts
  src/entities/user.entity.ts
  src/services/auth/auth.service.ts
  src/services/auth/dto/get-users.dto.ts
  src/services/auth/dto/patch-activation.dto.ts
Labels: Feat

#55 fix : createUser badges []로 초기화
  src/services/auth/auth.service.ts
Labels: Fix
